front-server:
  host: 'localhost:8442'
  access-token: xxx
server:
  app-name: xxx
  access-token: xxx
  cron: "0 0 8 * * ?"
db:
  host: 'xxx'
  port: 123
  user: ''
  password: ''
  dbName: ''
# 高德api
amap:
  host: ''
  key: ''