front-server:
  host: xxx
  port: 123
  access-token: xxx
server:
  app-name: xxx
  access-token: xxx
  cron: "8 * * * * ?"
db:
  host: 'xxx'
  port: 123
  user: ''
  password: ''
  dbName: ''
# 高德api
amap:
  host: ''
  key: ''